version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
        
  deploy:
    machine:
      enabled: true
    working_directory: ~/
    steps:
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: |
            ssh root@47.93.23.13 ls
      - add_ssh_keys:
          fingerprints:
            - "28:13:c0:41:c6:06:1f:8d:5c:93:8c:ac:29:ae:3c:9d"

workflows:
  maven_test:
    jobs:
      - maven/test
      - deploy